[package]
name = "prime-challenge"
version = "0.1.0"
authors = ["Wraithan (Chris McDonald) <xwraithanx@gmail.com>"]

[dependencies]
primal = "0.2.3"
time = "*"
scoped_threadpool = "*"

[dev-dependencies]
rand = "0.3"
